#!/bin/bash

export JENKINS_HOME=/opt/jenkins/data

exec java ${JAVA_ARGS} \
    -Duser.home=/opt/jenkins/data \
    -Djenkins.home=/opt/jenkins/data \
    -Djenkins.install.runSetupWizard=false \
    -Djenkins.model.Jenkins.slaveAgentPort=50000 \
    -jar /opt/jenkins/jenkins.war